version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd npm ci
      - run: cd npm test

  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:  npm ci
      - run:  npm run build

workflows:
  app:
    jobs:
      - test
      - build