version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Testing with Jest
          command: npx jest --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/results.xml
      - store_test_results:
          path: test-results

