version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/codegrid
    steps:
      - run: mkdir test-dir
      - run:
           command: pwd
           working_directory: test-dir