version: 2.1
jobs:
  www:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd www && npm ci
      - run: cd www && npm run build
      - run: cd www && npm test

  app:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd app && npm ci
      - run: cd app && npm run build
      - run: cd app && npm test

workflows:
  www_and_app:
    jobs:
      - www
      - app
