version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}-
            - npm-cache-
      - run: npm ci
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - save_cache:
          key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - package-lock.json
            - src/*

  test:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm test

  build:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run build

workflows:
  app:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
